// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Parcial.API.Data;

#nullable disable

namespace Parcial.API.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Parcial.Shared.Entities.EventControl", b =>
                {
                    b.Property<int>("Id_Boleta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Boleta"));

                    b.Property<DateTime?>("Fecha_De_Uso")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Fue_Usada")
                        .HasColumnType("bit");

                    b.Property<string>("Porteria")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Boleta");

                    b.HasIndex("Id_Boleta")
                        .IsUnique();

                    b.ToTable("eventControl");
                });
#pragma warning restore 612, 618
        }
    }
}
